# Generated by Django 4.2.13 on 2026-04-06 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='student.professor'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedules', to='student.professor'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.schoolyear'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.section'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'grade_level')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'grade_level', 'school_year')},
        ),
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together={('subject', 'section', 'school_year')},
        ),
    ]
